/*
This file is automatically generated by build.rs; DO NOT MANUALLY EDIT!
This header is designed to be consumed by ffigen over on the Dart side.
*/

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int32_t audiopc_default_output_sample_rate(void);

int32_t audiopc_default_output_channels(void);

int32_t audiopc_output_device_count(void);

int32_t audiopc_set_source_path(const char *path);

int32_t audiopc_set_source_url(const char *url);

int32_t audiopc_set_source_memory(const uint8_t *data, int32_t len);

int32_t audiopc_play(void);

int32_t audiopc_pause(void);

int32_t audiopc_stop(void);

int32_t audiopc_set_volume(double volume);

int32_t audiopc_set_lowpass_hz(double hz);

int32_t audiopc_set_max_queue_seconds(int32_t seconds);

int32_t audiopc_get_max_queue_seconds(void);

int32_t audiopc_buffered_samples(void);

int32_t audiopc_buffered_millis(void);

int32_t audiopc_is_playing(void);

int32_t audiopc_is_source_loaded(void);

int32_t audiopc_duration_millis(void);

int32_t audiopc_position_millis(void);

void audiopc_seek_millis(int32_t millis);
