// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../source.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_to_output`, `decode_and_feed`, `decoded_to_interleaved_f32`, `estimate_duration_millis`, `media_source_from_owned`, `media_source_from_ref`, `source_frame_sample`, `source_millis_to_output_samples`, `write_bytes_to_temp_file`
// These functions are ignored because they have generic arguments: `build`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DecodePool>>
abstract class DecodePool implements RustOpaqueInterface {
  int get duration;

  AudioSource? get source;

  set duration(int duration);

  set source(AudioSource? source);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DecodePool> newInstance() =>
      RustLib.instance.api.crateApiSourceDecodeDecodePoolNew();

  Future<void> setSource({required AudioSource source});

  Future<void> stop();
}
