// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_coefficients`, `db_to_linear`, `db_to_linear`, `linear_to_db`, `read_interpolated`, `read`, `shape`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioProcessor>>
abstract class AudioProcessor implements RustOpaqueInterface {
  static Future<AudioProcessor> default_() =>
      RustLib.instance.api.crateApiSourceFilterAudioProcessorDefault();

  /// Get processor name as string
  Future<void> name();

  /// Process a single sample
  Future<double> process({required double sample});

  /// Reset processor state
  Future<void> reset();

  /// Set a parameter by name (returns false if param not found)
  Future<bool> setParam({required String name, required double value});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BiquadFilter>>
abstract class BiquadFilter implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BiquadFilter> newInstance({
    required BiquadType filterType,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiSourceFilterBiquadFilterNew(
    filterType: filterType,
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setFrequency({required double freq});

  Future<void> setGain({required double gainDb});

  Future<void> setQ({required double q});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BitCrusher>>
abstract class BitCrusher implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BitCrusher> newInstance({required double sampleRate}) => RustLib
      .instance
      .api
      .crateApiSourceFilterBitCrusherNew(sampleRate: sampleRate);

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setBitDepth({required double bits});

  Future<void> setSampleRateReduction({required double factor});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Compressor>>
abstract class Compressor implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Compressor> newInstance({required double sampleRate}) => RustLib
      .instance
      .api
      .crateApiSourceFilterCompressorNew(sampleRate: sampleRate);

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setAttack({required double attackMs});

  Future<void> setMakeupGain({required double gainDb});

  Future<void> setRatio({required double ratio});

  Future<void> setRelease({required double releaseMs});

  Future<void> setThreshold({required double thresholdDb});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DCRemover>>
abstract class DcRemover implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DcRemover> newInstance({
    required double cutoffHz,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiSourceFilterDcRemoverNew(
    cutoffHz: cutoffHz,
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<void> reset();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DelayLine>>
abstract class DelayLine implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DelayLine> newInstance({
    required double maxDelayMs,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiSourceFilterDelayLineNew(
    maxDelayMs: maxDelayMs,
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setDelayTime({
    required double delayMs,
    required double sampleRate,
  });

  Future<void> setFeedback({required double feedback});

  Future<void> setMix({required double mix});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EnvelopeFollower>>
abstract class EnvelopeFollower implements RustOpaqueInterface {
  Future<double> getEnvelope();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<EnvelopeFollower> newInstance({required double sampleRate}) =>
      RustLib.instance.api.crateApiSourceFilterEnvelopeFollowerNew(
        sampleRate: sampleRate,
      );

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setAttack({required double attackMs});

  Future<void> setRelease({required double releaseMs});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Foldback>>
abstract class Foldback implements RustOpaqueInterface {
  static Future<Foldback> default_() =>
      RustLib.instance.api.crateApiSourceFilterFoldbackDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Foldback> newInstance() =>
      RustLib.instance.api.crateApiSourceFilterFoldbackNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setThreshold({required double threshold});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FractionalDelay>>
abstract class FractionalDelay implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FractionalDelay> newInstance({
    required double maxDelayMs,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiSourceFilterFractionalDelayNew(
    maxDelayMs: maxDelayMs,
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setDelayTime({
    required double delayMs,
    required double sampleRate,
  });

  Future<void> setFeedback({required double feedback});

  Future<void> setMix({required double mix});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Gain>>
abstract class Gain implements RustOpaqueInterface {
  static Future<Gain> default_() =>
      RustLib.instance.api.crateApiSourceFilterGainDefault();

  static Future<Gain> fromDb({required double db}) =>
      RustLib.instance.api.crateApiSourceFilterGainFromDb(db: db);

  Future<double> getGainDb();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Gain> newInstance() =>
      RustLib.instance.api.crateApiSourceFilterGainNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setGainDb({required double db});

  Future<void> setGainLinear({required double gain});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HardClipper>>
abstract class HardClipper implements RustOpaqueInterface {
  static Future<HardClipper> default_() =>
      RustLib.instance.api.crateApiSourceFilterHardClipperDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<HardClipper> newInstance() =>
      RustLib.instance.api.crateApiSourceFilterHardClipperNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setMix({required double mix});

  Future<void> setThreshold({required double threshold});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Limiter>>
abstract class Limiter implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Limiter> newInstance({required double sampleRate}) => RustLib
      .instance
      .api
      .crateApiSourceFilterLimiterNew(sampleRate: sampleRate);

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setRelease({required double releaseMs});

  Future<void> setThreshold({required double threshold});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MovingAverage>>
abstract class MovingAverage implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MovingAverage> newInstance({required BigInt length}) =>
      RustLib.instance.api.crateApiSourceFilterMovingAverageNew(length: length);

  Future<double> process({required double sample});

  Future<void> reset();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MuteSolo>>
abstract class MuteSolo implements RustOpaqueInterface {
  static Future<MuteSolo> default_() =>
      RustLib.instance.api.crateApiSourceFilterMuteSoloDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MuteSolo> newInstance() =>
      RustLib.instance.api.crateApiSourceFilterMuteSoloNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setAnySoloActive({required bool active});

  Future<void> setMute({required bool muted});

  Future<void> setSolo({required bool soloed});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoiseGate>>
abstract class NoiseGate implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<NoiseGate> newInstance({required double sampleRate}) => RustLib
      .instance
      .api
      .crateApiSourceFilterNoiseGateNew(sampleRate: sampleRate);

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setAttack({required double attackMs});

  Future<void> setHold({required double holdMs});

  Future<void> setRelease({required double releaseMs});

  Future<void> setThreshold({required double thresholdDb});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OnePoleHighPass>>
abstract class OnePoleHighPass implements RustOpaqueInterface {
  static Future<OnePoleHighPass> default_() =>
      RustLib.instance.api.crateApiSourceFilterOnePoleHighPassDefault();

  static Future<OnePoleHighPass> fromCutoff({
    required double cutoff,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiSourceFilterOnePoleHighPassFromCutoff(
    cutoff: cutoff,
    sampleRate: sampleRate,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<OnePoleHighPass> newInstance() =>
      RustLib.instance.api.crateApiSourceFilterOnePoleHighPassNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setCoefficient({required double coeff});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OnePoleLowPass>>
abstract class OnePoleLowPass implements RustOpaqueInterface {
  static Future<OnePoleLowPass> default_() =>
      RustLib.instance.api.crateApiSourceFilterOnePoleLowPassDefault();

  static Future<OnePoleLowPass> fromCutoff({
    required double cutoff,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiSourceFilterOnePoleLowPassFromCutoff(
    cutoff: cutoff,
    sampleRate: sampleRate,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<OnePoleLowPass> newInstance() =>
      RustLib.instance.api.crateApiSourceFilterOnePoleLowPassNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setCoefficient({required double coeff});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Panner>>
abstract class Panner implements RustOpaqueInterface {
  static Future<Panner> default_() =>
      RustLib.instance.api.crateApiSourceFilterPannerDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Panner> newInstance() =>
      RustLib.instance.api.crateApiSourceFilterPannerNew();

  Future<(double, double)> process({required double sample});

  Future<void> reset();

  Future<void> setPan({required double pan});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PhaseInverter>>
abstract class PhaseInverter implements RustOpaqueInterface {
  static Future<PhaseInverter> default_() =>
      RustLib.instance.api.crateApiSourceFilterPhaseInverterDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PhaseInverter> newInstance() =>
      RustLib.instance.api.crateApiSourceFilterPhaseInverterNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setInverted({required bool inverted});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RevertBuffer>>
abstract class RevertBuffer implements RustOpaqueInterface {
  Future<bool> isPlaying();

  Future<bool> isRecording();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RevertBuffer> newInstance({
    required double lengthMs,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiSourceFilterRevertBufferNew(
    lengthMs: lengthMs,
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setLoop({required bool loopPlayback});

  Future<void> setMix({required double mix});

  Future<void> startPlayback();

  Future<void> startRecording();

  Future<void> stop();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SVFOutputs>>
abstract class SvfOutputs implements RustOpaqueInterface {
  double get band;

  double get high;

  double get low;

  double get notch;

  set band(double band);

  set high(double high);

  set low(double low);

  set notch(double notch);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SampleAndHold>>
abstract class SampleAndHold implements RustOpaqueInterface {
  static Future<SampleAndHold> default_() =>
      RustLib.instance.api.crateApiSourceFilterSampleAndHoldDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SampleAndHold> newInstance() =>
      RustLib.instance.api.crateApiSourceFilterSampleAndHoldNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setTriggerThreshold({required double threshold});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SoftClipper>>
abstract class SoftClipper implements RustOpaqueInterface {
  static Future<SoftClipper> default_() =>
      RustLib.instance.api.crateApiSourceFilterSoftClipperDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SoftClipper> newInstance() =>
      RustLib.instance.api.crateApiSourceFilterSoftClipperNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setDrive({required double drive});

  Future<void> setMix({required double mix});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StateVariableFilter>>
abstract class StateVariableFilter implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<StateVariableFilter> newInstance({
    required double sampleRate,
  }) => RustLib.instance.api.crateApiSourceFilterStateVariableFilterNew(
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<SvfOutputs> processAll({required double sample});

  Future<void> reset();

  Future<void> setFrequency({required double freq});

  Future<void> setResonance({required double res});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WaveShaper>>
abstract class WaveShaper implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WaveShaper> newInstance({required WaveShapeCurve curveType}) =>
      RustLib.instance.api.crateApiSourceFilterWaveShaperNew(
        curveType: curveType,
      );

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setAmount({required double amount});

  Future<void> setCurve({required WaveShapeCurve curve});
}

/// Biquad Filter Types
enum BiquadType {
  lowPass,
  highPass,
  bandPass,
  notch,
  peaking,
  lowShelf,
  highShelf,
  allPass,
}

/// Waveshaper curve types
enum WaveShapeCurve { soft, hard, asymmetric, sine, quadratic }
