// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `byte_len`, `is_seekable`, `read`, `seek`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Client>>
abstract class Client implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HttpStream>>
abstract class HttpStream implements RustOpaqueInterface {
  Client get client;

  BigInt? get len;

  BigInt get pos;

  Url get url;

  set client(Client client);

  set len(BigInt? len);

  set pos(BigInt pos);

  set url(Url url);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<HttpStream> newInstance({required String urlStr}) => RustLib
      .instance
      .api
      .crateApiSourceHttpStreamHttpStreamNew(urlStr: urlStr);

  Future<void> sendRangeRequest({required BigInt start});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Url>>
abstract class Url implements RustOpaqueInterface {}
