// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `read_interpolated`, `read`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DelayLine>>
abstract class DelayLine implements RustOpaqueInterface {
  Future<double> feedback();

  Future<double> mix();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DelayLine> newInstance({
    required double maxDelayMs,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiFiltersDelayDelayLineNew(
    maxDelayMs: maxDelayMs,
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setDelayTime({
    required double delayMs,
    required double sampleRate,
  });

  Future<void> setFeedback({required double feedback});

  Future<void> setMix({required double mix});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FractionalDelay>>
abstract class FractionalDelay implements RustOpaqueInterface {
  Future<double> feedback();

  Future<double> mix();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FractionalDelay> newInstance({
    required double maxDelayMs,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiFiltersDelayFractionalDelayNew(
    maxDelayMs: maxDelayMs,
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setDelayTime({
    required double delayMs,
    required double sampleRate,
  });

  Future<void> setFeedback({required double feedback});

  Future<void> setMix({required double mix});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RevertBuffer>>
abstract class RevertBuffer implements RustOpaqueInterface {
  Future<bool> isPlaying();

  Future<bool> isRecording();

  Future<double> mix();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RevertBuffer> newInstance({
    required double lengthMs,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiFiltersDelayRevertBufferNew(
    lengthMs: lengthMs,
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setLoop({required bool loopPlayback});

  Future<void> setMix({required double mix});

  Future<void> startPlayback();

  Future<void> startRecording();

  Future<void> stop();
}
