// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../filters.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `shape`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BitCrusher>>
abstract class BitCrusher implements RustOpaqueInterface {
  Future<double> bitDepth();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BitCrusher> newInstance({required double sampleRate}) => RustLib
      .instance
      .api
      .crateApiFiltersDistortionBitCrusherNew(sampleRate: sampleRate);

  Future<double> process({required double sample});

  Future<double> rateReduction();

  Future<void> reset();

  Future<void> setBitDepth({required double v});

  Future<void> setSampleRateReduction({required double v});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Foldback>>
abstract class Foldback implements RustOpaqueInterface {
  static Future<Foldback> default_() =>
      RustLib.instance.api.crateApiFiltersDistortionFoldbackDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Foldback> newInstance() =>
      RustLib.instance.api.crateApiFiltersDistortionFoldbackNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setThreshold({required double v});

  Future<double> threshold();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HardClipper>>
abstract class HardClipper implements RustOpaqueInterface {
  static Future<HardClipper> default_() =>
      RustLib.instance.api.crateApiFiltersDistortionHardClipperDefault();

  Future<double> mix();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<HardClipper> newInstance() =>
      RustLib.instance.api.crateApiFiltersDistortionHardClipperNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setMix({required double v});

  Future<void> setThreshold({required double v});

  Future<double> threshold();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SoftClipper>>
abstract class SoftClipper implements RustOpaqueInterface {
  static Future<SoftClipper> default_() =>
      RustLib.instance.api.crateApiFiltersDistortionSoftClipperDefault();

  Future<double> drive();

  Future<double> mix();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SoftClipper> newInstance() =>
      RustLib.instance.api.crateApiFiltersDistortionSoftClipperNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setDrive({required double v});

  Future<void> setMix({required double v});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WaveShaper>>
abstract class WaveShaper implements RustOpaqueInterface {
  Future<double> amount();

  Future<WaveShapeCurve> curve();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WaveShaper> newInstance({required WaveShapeCurve curve}) =>
      RustLib.instance.api.crateApiFiltersDistortionWaveShaperNew(curve: curve);

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setAmount({required double v});

  Future<void> setCurve({required WaveShapeCurve v});
}
