// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `db_to_linear`, `db_to_linear`, `linear_to_db`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Compressor>>
abstract class Compressor implements RustOpaqueInterface {
  Future<double> attack();

  Future<double> makeupGain();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Compressor> newInstance({required double sampleRate}) => RustLib
      .instance
      .api
      .crateApiFiltersDynamicsCompressorNew(sampleRate: sampleRate);

  Future<double> process({required double sample});

  Future<double> ratio();

  Future<double> release();

  Future<void> reset();

  Future<void> setAttack({required double v});

  Future<void> setMakeupGain({required double v});

  Future<void> setRatio({required double v});

  Future<void> setRelease({required double v});

  Future<void> setThreshold({required double v});

  Future<double> threshold();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EnvelopeFollower>>
abstract class EnvelopeFollower implements RustOpaqueInterface {
  Future<double> attack();

  Future<double> getEnvelope();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<EnvelopeFollower> newInstance({required double sampleRate}) =>
      RustLib.instance.api.crateApiFiltersDynamicsEnvelopeFollowerNew(
        sampleRate: sampleRate,
      );

  Future<double> process({required double sample});

  Future<double> release();

  Future<void> reset();

  Future<void> setAttack({required double v});

  Future<void> setRelease({required double v});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Limiter>>
abstract class Limiter implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Limiter> newInstance({required double sampleRate}) => RustLib
      .instance
      .api
      .crateApiFiltersDynamicsLimiterNew(sampleRate: sampleRate);

  Future<double> process({required double sample});

  Future<double> release();

  Future<void> reset();

  Future<void> setRelease({required double v});

  Future<void> setThreshold({required double v});

  Future<double> threshold();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoiseGate>>
abstract class NoiseGate implements RustOpaqueInterface {
  Future<double> attack();

  Future<double> hold();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<NoiseGate> newInstance({required double sampleRate}) => RustLib
      .instance
      .api
      .crateApiFiltersDynamicsNoiseGateNew(sampleRate: sampleRate);

  Future<double> process({required double sample});

  Future<double> release();

  Future<void> reset();

  Future<void> setAttack({required double v});

  Future<void> setHold({required double v});

  Future<void> setRelease({required double v});

  Future<void> setThreshold({required double v});

  Future<double> threshold();
}
