// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DCRemover>>
abstract class DcRemover implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DcRemover> newInstance({
    required double cutoffHz,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiFiltersUtilitiesDcRemoverNew(
    cutoffHz: cutoffHz,
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<void> reset();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Gain>>
abstract class Gain implements RustOpaqueInterface {
  static Future<Gain> default_() =>
      RustLib.instance.api.crateApiFiltersUtilitiesGainDefault();

  static Future<Gain> fromDb({required double db}) =>
      RustLib.instance.api.crateApiFiltersUtilitiesGainFromDb(db: db);

  Future<double> gainDb();

  Future<double> gainLinear();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Gain> newInstance() =>
      RustLib.instance.api.crateApiFiltersUtilitiesGainNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setGainDb({required double db});

  Future<void> setGainLinear({required double v});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MuteSolo>>
abstract class MuteSolo implements RustOpaqueInterface {
  static Future<MuteSolo> default_() =>
      RustLib.instance.api.crateApiFiltersUtilitiesMuteSoloDefault();

  Future<bool> isMuted();

  Future<bool> isSoloed();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MuteSolo> newInstance() =>
      RustLib.instance.api.crateApiFiltersUtilitiesMuteSoloNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setAnySoloActive({required bool v});

  Future<void> setMute({required bool v});

  Future<void> setSolo({required bool v});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Panner>>
abstract class Panner implements RustOpaqueInterface {
  static Future<Panner> default_() =>
      RustLib.instance.api.crateApiFiltersUtilitiesPannerDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Panner> newInstance() =>
      RustLib.instance.api.crateApiFiltersUtilitiesPannerNew();

  Future<double> pan();

  Future<(double, double)> process({required double sample});

  Future<void> reset();

  Future<void> setPan({required double v});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PhaseInverter>>
abstract class PhaseInverter implements RustOpaqueInterface {
  static Future<PhaseInverter> default_() =>
      RustLib.instance.api.crateApiFiltersUtilitiesPhaseInverterDefault();

  Future<bool> isInverted();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PhaseInverter> newInstance() =>
      RustLib.instance.api.crateApiFiltersUtilitiesPhaseInverterNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setInverted({required bool v});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SampleAndHold>>
abstract class SampleAndHold implements RustOpaqueInterface {
  static Future<SampleAndHold> default_() =>
      RustLib.instance.api.crateApiFiltersUtilitiesSampleAndHoldDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SampleAndHold> newInstance() =>
      RustLib.instance.api.crateApiFiltersUtilitiesSampleAndHoldNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setTriggerThreshold({required double v});

  Future<double> triggerThreshold();
}
