// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `write_output_f32`, `write_output_i16`, `write_output_u16`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Mutex < AudioState > >>>
abstract class ArcMutexAudioState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioOutput>>
abstract class AudioOutput implements RustOpaqueInterface {
  SenderAudioCommand get cmdTx;

  SupportedStreamConfig get outConfig;

  ArcMutexAudioState get state;

  set cmdTx(SenderAudioCommand cmdTx);

  set outConfig(SupportedStreamConfig outConfig);

  set state(ArcMutexAudioState state);

  Future<void> build();

  static Future<StreamConfig> getConfig() =>
      RustLib.instance.api.crateApiRendererOutputAudioOutputGetConfig();

  static Future<SupportedStreamConfig> getOutputConfig() =>
      RustLib.instance.api.crateApiRendererOutputAudioOutputGetOutputConfig();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AudioOutput> newInstance({
    required SenderAudioCommand cmdTx,
    required ArcMutexAudioState state,
    required SupportedStreamConfig outConfig,
  }) => RustLib.instance.api.crateApiRendererOutputAudioOutputNew(
    cmdTx: cmdTx,
    state: state,
    outConfig: outConfig,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Sender < AudioCommand >>>
abstract class SenderAudioCommand implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StreamConfig>>
abstract class StreamConfig implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SupportedStreamConfig>>
abstract class SupportedStreamConfig implements RustOpaqueInterface {}
