// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioState>>
abstract class AudioState implements RustOpaqueInterface {
  /// Clear all transient audio state without touching volume / rate / device.
  Future<void> clearAudioState();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AudioState> newInstance({
    required BuffConfig config,
    required BuffConfig vConfig,
    required BigInt channels,
  }) => RustLib.instance.api.crateApiRendererStateAudioStateNew(
    config: config,
    vConfig: vConfig,
    channels: channels,
  );

  Future<double> nextSample({required BigInt channels});

  /// Current playback position in milliseconds.
  Future<int> position();

  /// Push up to `max_samples - queue.len()` samples.  Returns the count
  /// actually pushed; caller retries the rest after sleeping.
  Future<BigInt> pushSamplesBounded({required List<double> samples});

  Future<void> pushVisualizerSample({required double sample});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ResampleState>>
abstract class ResampleState implements RustOpaqueInterface {
  static Future<ResampleState> default_() =>
      RustLib.instance.api.crateApiRendererStateResampleStateDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ResampleState> newInstance() =>
      RustLib.instance.api.crateApiRendererStateResampleStateNew();

  Future<void> reset();
}

class BuffConfig {
  final int sampleRate;
  final BigInt maxSamples;
  final BigInt mQueueSec;

  const BuffConfig({
    required this.sampleRate,
    required this.maxSamples,
    required this.mQueueSec,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BuffConfig> newInstance({
    required BigInt maxSamples,
    required BigInt mQueueSec,
    required int sampleRate,
  }) => RustLib.instance.api.crateApiRendererStateBuffConfigNew(
    maxSamples: maxSamples,
    mQueueSec: mQueueSec,
    sampleRate: sampleRate,
  );

  @override
  int get hashCode =>
      sampleRate.hashCode ^ maxSamples.hashCode ^ mQueueSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuffConfig &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          maxSamples == other.maxSamples &&
          mQueueSec == other.mQueueSec;
}

enum PlaybackState {
  idle,
  buffering,
  playing,
  paused,
  stopped,
  completed;

  Future<int> id() =>
      RustLib.instance.api.crateApiRendererStatePlaybackStateId(that: this);
}
