// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../source/filter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'state.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioState>>
abstract class AudioState implements RustOpaqueInterface {
  List<AudioProcessor> get effects;

  BigInt get emittedSamples;

  double get plRate;

  PlaybackState get plState;

  VecDequeF32 get queue;

  int get startMillies;

  bool get streamEnded;

  int get underrunCount;

  VecDequeF32 get visualizer;

  double get volumn;

  set effects(List<AudioProcessor> effects);

  set emittedSamples(BigInt emittedSamples);

  set plRate(double plRate);

  set plState(PlaybackState plState);

  set queue(VecDequeF32 queue);

  set startMillies(int startMillies);

  set streamEnded(bool streamEnded);

  set underrunCount(int underrunCount);

  set visualizer(VecDequeF32 visualizer);

  set volumn(double volumn);

  /// Clear all transient audio state without touching volume / rate / device.
  Future<void> clearAudioState();

  Future<int> computeMillies({
    required BigInt sourcePos,
    required BigInt channels,
  });

  Future<BigInt> computeSource({required int channels});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AudioState> newInstance({
    required int startMillies,
    required BuffConfig config,
    required BuffConfig vConfig,
  }) => RustLib.instance.api.crateApiRendererStateAudioStateNew(
    startMillies: startMillies,
    config: config,
    vConfig: vConfig,
  );

  Future<double> nextSample({required BigInt channels});

  /// Current playback position in milliseconds.
  Future<int> position({required BigInt outChannels});

  /// Push up to `max_samples - queue.len()` samples.  Returns the count
  /// actually pushed; caller retries the rest after sleeping.
  Future<BigInt> pushSamplesBounded({required List<double> samples});

  Future<void> pushVisualizerSample({required double sample});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ResampleState>>
abstract class ResampleState implements RustOpaqueInterface {
  Float32List get carry;

  double get pos;

  set carry(Float32List carry);

  set pos(double pos);

  static Future<ResampleState> default_() =>
      RustLib.instance.api.crateApiRendererStateResampleStateDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ResampleState> newInstance() =>
      RustLib.instance.api.crateApiRendererStateResampleStateNew();

  Future<void> reset();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VecDeque < f32 >>>
abstract class VecDequeF32 implements RustOpaqueInterface {}

class BuffConfig {
  final int sampleRate;
  final BigInt maxSamples;
  final BigInt mQueueSec;

  const BuffConfig({
    required this.sampleRate,
    required this.maxSamples,
    required this.mQueueSec,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BuffConfig> newInstance({
    required BigInt maxSamples,
    required BigInt mQueueSec,
    required int sampleRate,
  }) => RustLib.instance.api.crateApiRendererStateBuffConfigNew(
    maxSamples: maxSamples,
    mQueueSec: mQueueSec,
    sampleRate: sampleRate,
  );

  @override
  int get hashCode =>
      sampleRate.hashCode ^ maxSamples.hashCode ^ mQueueSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuffConfig &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          maxSamples == other.maxSamples &&
          mQueueSec == other.mQueueSec;
}

@freezed
sealed class PlaybackState with _$PlaybackState {
  const PlaybackState._();

  const factory PlaybackState.idle() = PlaybackState_Idle;
  const factory PlaybackState.buffering() = PlaybackState_Buffering;
  const factory PlaybackState.playing() = PlaybackState_Playing;
  const factory PlaybackState.paused() = PlaybackState_Paused;
  const factory PlaybackState.stopped() = PlaybackState_Stopped;
  const factory PlaybackState.completed() = PlaybackState_Completed;
  const factory PlaybackState.error(String field0) = PlaybackState_Error;
}
