// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_coefficients`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `hash`, `hash`, `hash`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioProcessor>>
abstract class AudioProcessor implements RustOpaqueInterface {
  static Future<AudioProcessor> default_() =>
      RustLib.instance.api.crateApiFiltersAudioProcessorDefault();

  /// Get a float parameter value
  Future<double> get_({required Param param});

  /// Get processor name
  Future<void> name();

  /// Process a single sample
  Future<double> process({required double sample});

  /// Reset processor state
  Future<void> reset();

  /// Set a float parameter
  Future<void> set_({required Param param, required double value});

  /// Get list of valid params for this processor
  Future<void> validParams();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BiquadFilter>>
abstract class BiquadFilter implements RustOpaqueInterface {
  Future<double> frequency();

  Future<double> gainDb();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BiquadFilter> newInstance({
    required BiquadType filterType,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiFiltersBiquadFilterNew(
    filterType: filterType,
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<double> q();

  Future<void> reset();

  Future<void> setFrequency({required double freq});

  Future<void> setGain({required double gainDb});

  Future<void> setQ({required double q});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MovingAverage>>
abstract class MovingAverage implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MovingAverage> newInstance({required BigInt length}) =>
      RustLib.instance.api.crateApiFiltersMovingAverageNew(length: length);

  Future<double> process({required double sample});

  Future<void> reset();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OnePoleHighPass>>
abstract class OnePoleHighPass implements RustOpaqueInterface {
  Future<double> coefficient();

  static Future<OnePoleHighPass> default_() =>
      RustLib.instance.api.crateApiFiltersOnePoleHighPassDefault();

  static Future<OnePoleHighPass> fromCutoff({
    required double cutoff,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiFiltersOnePoleHighPassFromCutoff(
    cutoff: cutoff,
    sampleRate: sampleRate,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<OnePoleHighPass> newInstance() =>
      RustLib.instance.api.crateApiFiltersOnePoleHighPassNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setCoefficient({required double coeff});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OnePoleLowPass>>
abstract class OnePoleLowPass implements RustOpaqueInterface {
  Future<double> coefficient();

  static Future<OnePoleLowPass> default_() =>
      RustLib.instance.api.crateApiFiltersOnePoleLowPassDefault();

  static Future<OnePoleLowPass> fromCutoff({
    required double cutoff,
    required double sampleRate,
  }) => RustLib.instance.api.crateApiFiltersOnePoleLowPassFromCutoff(
    cutoff: cutoff,
    sampleRate: sampleRate,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<OnePoleLowPass> newInstance() =>
      RustLib.instance.api.crateApiFiltersOnePoleLowPassNew();

  Future<double> process({required double sample});

  Future<void> reset();

  Future<void> setCoefficient({required double coeff});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SVFOutputs>>
abstract class SvfOutputs implements RustOpaqueInterface {
  double get band;

  double get high;

  double get low;

  double get notch;

  set band(double band);

  set high(double high);

  set low(double low);

  set notch(double notch);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StateVariableFilter>>
abstract class StateVariableFilter implements RustOpaqueInterface {
  Future<double> frequency();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<StateVariableFilter> newInstance({
    required double sampleRate,
  }) => RustLib.instance.api.crateApiFiltersStateVariableFilterNew(
    sampleRate: sampleRate,
  );

  Future<double> process({required double sample});

  Future<SvfOutputs> processAll({required double sample});

  Future<void> reset();

  Future<double> resonance();

  Future<void> setFrequency({required double freq});

  Future<void> setResonance({required double res});
}

/// Biquad filter types
enum BiquadType {
  lowPass,
  highPass,
  bandPass,
  notch,
  peaking,
  lowShelf,
  highShelf,
  allPass,
}

/// All possible parameter identifiers
enum Param {
  coefficient,
  frequency,
  resonance,
  q,
  gainDb,
  filterLength,
  delayMs,
  feedback,
  mix,
  loopPlayback,
  threshold,
  ratio,
  attack,
  release,
  hold,
  makeupGain,
  drive,
  bitDepth,
  rateReduction,
  amount,
  curveType,
  gainLinear,
  pan,
  mute,
  solo,
  anySoloActive,
  triggerThreshold,
  inverted,
  sampleRate,
}

/// Error type for parameter operations
enum ParamError { invalidParam, invalidValue }

/// Wave shape curve types
enum WaveShapeCurve { soft, hard, asymmetric, sine, quadratic }
