// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'filters.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'renderer/output.dart';
import 'source.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioPlayer>>
abstract class AudioPlayer implements RustOpaqueInterface {
  /// Add Effect to output audio.
  Future<void> addEffect({required AudioProcessor effect});

  /// Clear the effect chain of every output channel.
  Future<void> clearEffects();

  /// Duration in millisecond of current source.
  int durationMillis();

  AudioOutputConfig getOutputConfig();

  Future<int> getState();

  bool isCompleted();

  /// Whether player is playing or not.
  bool isPlaying();

  factory AudioPlayer() => RustLib.instance.api.crateApiPlayerAudioPlayerNew();

  /// Pause curent playing song.
  void pause();

  /// Play current audio source. If current source is empty then an error will be throw.
  void play();

  Future<int> position();

  void resume();

  Future<Float32List> samplesData();

  /// Play audio at given position in millisecond.
  void seek({required int position});

  /// Set playback speed of output audio.
  Future<void> setRate({required double rate});

  /// Set source for preparing to play.
  void setSource({required AudioSource source});

  /// Set volume of ouput audio.
  Future<void> setVolumn({required double volumn});

  /// Stop current playing audio.
  Future<void> stop();
}
