// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'source.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioPlayer>>
abstract class AudioPlayer implements RustOpaqueInterface {
  Future<bool> isPlaying();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AudioPlayer> newInstance() =>
      RustLib.instance.api.crateApiPlayerAudioPlayerNew();

  Future<void> play();

  Future<void> seek({required int position});

  Future<void> setSource({required AudioSource source});

  Future<void> setVolume({required double volume});

  Future<void> stop();
}
