// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'source.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

@freezed
sealed class AudioSource with _$AudioSource {
  const AudioSource._();

  /// A path to a local file (absolute or relative).
  const factory AudioSource.path(String field0) = AudioSource_Path;

  /// An HTTP/HTTPS URL.  The engine opens a streaming connection on first
  /// use via [`crate::http_stream::HttpStream`].
  const factory AudioSource.url(String field0) = AudioSource_Url;

  /// Raw bytes already loaded into memory (e.g., loaded from an asset
  /// bundle or received over IPC).  Written to a temporary file before
  /// handing to Symphonia so that seeking works correctly.
  const factory AudioSource.memory(Uint8List field0) = AudioSource_Memory;

  /// Returns a human-readable description, suitable for logging.
  Future<String> description() =>
      RustLib.instance.api.crateApiSourceAudioSourceDescription(that: this);

  /// Returns `true` if the source is a network URL.
  Future<bool> isRemote() =>
      RustLib.instance.api.crateApiSourceAudioSourceIsRemote(that: this);
}
