// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decay_bands`, `ensure_band_states`, `hann_window`, `hz_to_bin`, `log_interp`, `perform_fft`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `hash`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VisualizerProcessor>>
abstract class VisualizerProcessor implements RustOpaqueInterface {
  /// Standalone band analysis — performs its own FFT.
  Future<List<BandEnergy>> analyzeBands({
    required List<double> samples,
    required BigInt channels,
    required int sampleRate,
    required List<BandKind> kinds,
    required bool playing,
  });

  /// Composite bass hit strength (kick + bass).
  static Future<double> bassBeat({required List<BandEnergy> bands}) => RustLib
      .instance
      .api
      .crateApiVisualizerVisualizerProcessorBassBeat(bands: bands);

  /// Maximum beat value across bands matching the requested kinds.
  static Future<double> beatForKinds({
    required List<BandEnergy> bands,
    required List<BandKind> kinds,
  }) => RustLib.instance.api.crateApiVisualizerVisualizerProcessorBeatForKinds(
    bands: bands,
    kinds: kinds,
  );

  Future<Float32List> compute({
    required List<double> samples,
    required BigInt channels,
    required int sampleRate,
    required bool playing,
  });

  /// Compute band energies using cached magnitudes from the last
  /// `compute()` or `analyze_bands()` call. Near-zero cost.
  Future<List<BandEnergy>> computeBands({required List<BandKind> kinds});

  Future<Float32List> decayOnly();

  /// Composite drum hit strength (kick + snare body + snare crack + toms).
  static Future<double> drumBeat({required List<BandEnergy> bands}) => RustLib
      .instance
      .api
      .crateApiVisualizerVisualizerProcessorDrumBeat(bands: bands);

  Future<void> ensureBarCount({required BigInt count});

  /// High-frequency energy (hi-hat, cymbals, sibilance) as max normalized
  /// value across bands starting at 4 kHz or above.
  static Future<double> highFrequencyEnergy({
    required List<BandEnergy> bands,
  }) => RustLib.instance.api
      .crateApiVisualizerVisualizerProcessorHighFrequencyEnergy(bands: bands);

  /// Low-frequency energy (sub bass + bass) as max normalized value
  /// across bands below 250 Hz.
  static Future<double> lowFrequencyEnergy({required List<BandEnergy> bands}) =>
      RustLib.instance.api
          .crateApiVisualizerVisualizerProcessorLowFrequencyEnergy(
            bands: bands,
          );

  factory VisualizerProcessor({
    required BigInt barCount,
    required BigInt fftSize,
  }) => RustLib.instance.api.crateApiVisualizerVisualizerProcessorNew(
    barCount: barCount,
    fftSize: fftSize,
  );

  Future<void> reset();

  /// Vocal presence as normalized energy.
  static Future<double> vocalPresence({required List<BandEnergy> bands}) =>
      RustLib.instance.api.crateApiVisualizerVisualizerProcessorVocalPresence(
        bands: bands,
      );
}

/// Computed energy metrics for a single frequency band.
class BandEnergy {
  /// The band category analyzed.
  final BandKind kind;

  /// Lower frequency bound in Hz.
  final double minHz;

  /// Upper frequency bound in Hz.
  final double maxHz;

  /// Raw average magnitude in this band this frame.
  final double raw;

  /// Time-smoothed energy (fast attack, slow release).
  final double smoothed;

  /// Peak hold value (slowly decaying).
  final double peak;

  /// Normalized energy (0–1), relative to this band's adaptive level.
  final double normalized;

  /// Transient / onset strength (0–1). Higher = percussive hit detected.
  final double beat;

  const BandEnergy({
    required this.kind,
    required this.minHz,
    required this.maxHz,
    required this.raw,
    required this.smoothed,
    required this.peak,
    required this.normalized,
    required this.beat,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      minHz.hashCode ^
      maxHz.hashCode ^
      raw.hashCode ^
      smoothed.hashCode ^
      peak.hashCode ^
      normalized.hashCode ^
      beat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BandEnergy &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          minHz == other.minHz &&
          maxHz == other.maxHz &&
          raw == other.raw &&
          smoothed == other.smoothed &&
          peak == other.peak &&
          normalized == other.normalized &&
          beat == other.beat;
}

/// Enum representing different frequency bands / instruments.
/// Each variant knows its own frequency range.
enum BandKind {
  subBass,
  bass,
  upperBass,
  lowMid,
  mid,
  upperMid,
  presence,
  high,
  brilliance,
  air,
  kick,
  snareBody,
  snareCrack,
  toms,
  vocal,
  hiHat,
  cymbals;

  /// Detailed 10-band breakdown with finer mid-range resolution.
  static Future<List<BandKind>> detailed() =>
      RustLib.instance.api.crateApiVisualizerBandKindDetailed();

  /// Returns the (min_hz, max_hz) frequency range for this band kind.
  Future<(double, double)> freqRange() =>
      RustLib.instance.api.crateApiVisualizerBandKindFreqRange(that: this);

  /// Instrument-approximation bands (overlapping ranges).
  static Future<List<BandKind>> instrument() =>
      RustLib.instance.api.crateApiVisualizerBandKindInstrument();

  /// Standard frequency bands covering the full audible spectrum.
  static Future<List<BandKind>> standard() =>
      RustLib.instance.api.crateApiVisualizerBandKindStandard();
}

/// Internal per-band smoothing state.
class BandState {
  final double smoothed;
  final double peak;
  final double fastEnergy;
  final double slowEnergy;
  final double adaptiveLevel;

  const BandState({
    required this.smoothed,
    required this.peak,
    required this.fastEnergy,
    required this.slowEnergy,
    required this.adaptiveLevel,
  });

  static Future<BandState> default_() =>
      RustLib.instance.api.crateApiVisualizerBandStateDefault();

  @override
  int get hashCode =>
      smoothed.hashCode ^
      peak.hashCode ^
      fastEnergy.hashCode ^
      slowEnergy.hashCode ^
      adaptiveLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BandState &&
          runtimeType == other.runtimeType &&
          smoothed == other.smoothed &&
          peak == other.peak &&
          fastEnergy == other.fastEnergy &&
          slowEnergy == other.slowEnergy &&
          adaptiveLevel == other.adaptiveLevel;
}
